const nav=document.getElementById("nav"),menu=document.querySelector(".menu"),links=document.getElementById("links"),form=document.getElementById("bookingForm"),pkg=document.getElementById("package"),toast=document.getElementById("toast"),progress=document.getElementById("progress");
window.addEventListener("scroll",()=>{nav.classList.toggle("scrolled",scrollY>25);progress.style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+"%"});
menu.onclick=()=>links.classList.toggle("open");document.querySelectorAll("#links a").forEach(a=>a.onclick=()=>links.classList.remove("open"));
document.querySelectorAll(".reveal").forEach(e=>new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add("visible")}}),{threshold:.1}).observe(e));
function selectPackage(p){pkg.value=p;document.getElementById("booking").scrollIntoView({behavior:"smooth"})}
document.querySelectorAll(".choose,.type-card").forEach(b=>b.onclick=()=>selectPackage(b.dataset.p));

form.onsubmit=e=>{e.preventDefault();let d=new FormData(form);let body=`📸 NEW NNT STUDIO BOOKING\n\nName: ${d.get("name")}\nPhone: ${d.get("phone")}\nPackage: ${d.get("package")}\nDate: ${d.get("date")}\nTime: ${d.get("time")}\nLocation: ${d.get("location")}\nMessage: ${d.get("message")||"None"}\n\n— NNT STUDIO website booking`;if(d.get("method")==="whatsapp")window.open("https://wa.me/94741692115?text="+encodeURIComponent(body),"_blank");else location.href="mailto:tharulamarasinghe16@gmail.com?subject="+encodeURIComponent("New NNT STUDIO Booking — "+d.get("name"))+"&body="+encodeURIComponent(body);showToast("Booking request prepared ✓","Your selected contact method should now be open.")};

const messages=document.getElementById("messages"),question=document.getElementById("question"),ask=document.getElementById("ask");
function answer(q){q=q.toLowerCase();if(q.includes("best")||q.includes("package"))return"Standard is the most popular: 40 edited photos for Rs. 4,000–5,000. Premium gives 60 photos; Events are best for full coverage.";if(q.includes("bring"))return"Bring outfits you love, personal items that fit your concept, and your ideas. For events, share the venue and schedule when booking.";if(q.includes("book"))return"Fill the form, choose WhatsApp or Email, then press Send. NNT STUDIO confirms the final appointment.";if(q.includes("price")||q.includes("cost"))return"Basic Rs. 3,500–4,000 · Standard Rs. 4,000–5,000 · Premium Rs. 5,000–6,000 · Events Rs. 10,000–15,000.";return"I can help with packages, pricing, booking, or shoot preparation. Try asking about the best package 😊."}
function send(){let q=question.value.trim();if(!q)return;addBubble(q,"user");question.value="";setTimeout(()=>addBubble(answer(q),"bot"),250)}
function addBubble(t,c){let d=document.createElement("div");d.className="bubble "+c;d.textContent=t;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
ask.onclick=send;question.onkeydown=e=>{if(e.key==="Enter")send()};document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>{question.value=b.dataset.q;send()});

const modal=document.getElementById("reviewModal");document.getElementById("openReview").onclick=()=>modal.classList.add("open");document.getElementById("closeReview").onclick=()=>modal.classList.remove("open");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("open")};
document.getElementById("reviewForm").onsubmit=e=>{e.preventDefault();let d=new FormData(e.target);let body=`⭐ NNT STUDIO REVIEW SUBMISSION\n\nName: ${d.get("rname")}\nRating: ${d.get("rating")}\nReview: ${d.get("review")}\n\nPlease review and approve this testimonial for the NNT STUDIO website.`;window.open("https://wa.me/94741692115?text="+encodeURIComponent(body),"_blank");modal.classList.remove("open");e.target.reset();showToast("Review ready to send ✓","Your review has been prepared in WhatsApp for NNT STUDIO to approve and publish.")};
function showToast(title,text){document.getElementById("toastTitle").textContent=title;document.getElementById("toastText").textContent=text;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),5500)}